task: add missing NEM transaction schemas
symbol/catbuffer-schemas pull request #15
Opened 2021-09-03 19:11 UTC by Jaguar0625

2021-09-06 14:23 UTC, gimre-xymcity requested changes

2021-09-06 14:23 UTC, gimre-xymcity commented on nem/account_key_link/account_key_link.cats
> +	remote_public_key = inline SizePrefixedPublicKey
hmm, shouldn't name match what we have in json repr? :/

("remoteAccount" in this case and "mode" above)

(and probably same thing in prev review)


I think the answer is _NOT_, but in this case, shouldn't we create _breaking_ NEM update 😬

2021-09-06 14:23 UTC, gimre-xymcity commented on nem/mosaic/mosaic_supply_change.cats
> +	delta = Amount
technically, this is of type Supply not Amount
(Supply allows negatives, Amount does not)

2021-09-06 14:23 UTC, gimre-xymcity commented on nem/multisig/multisig.cats
> +	cosignatures = array(Cosignature, cosignatures_count)
this whole part is optional, isn't it?

2021-09-06 14:23 UTC, gimre-xymcity commented on nem/multisig/multisig_account_modification.cats
> +	modifications = array(MultisigAccountModification, modifications_count)
this is doubled, as this is already present in MultisigAccountModificationTransaction

2021-09-06 14:23 UTC, gimre-xymcity commented on nem/multisig/multisig_account_modification.cats
> +	min_approval_delta = uint32
int32?

2021-09-06 14:23 UTC, gimre-xymcity commented on nem/namespace/namespace_registration.cats
> +	parent_name = array(int8, parent_name_size) if 0xFFFFFFFF not equals parent_name_size
I know what this is but - 😭

2021-09-06 17:48 UTC, Jaguar0625 commented on nem/mosaic/mosaic_definition.cats
> +struct MosaicProperty
catbuffer doesn't currently have a string type. we could add that but not sure about it? unless you just mean a comment?

2021-09-06 17:50 UTC, Jaguar0625 commented on nem/account_key_link/account_key_link.cats
> +	remote_public_key = inline SizePrefixedPublicKey
i had tried to update all the names to match the symbol name so it would be easier for users. we could make an update to NIS with the renames, but, if we did, we'd probably want some backwards compat to not break all clients. 😅

2021-09-06 17:52 UTC, Jaguar0625 commented on nem/multisig/multisig.cats
> +	cosignatures = array(Cosignature, cosignatures_count)
how do mean?

2021-09-06 17:53 UTC, Jaguar0625 commented on nem/multisig/multisig_account_modification.cats
> +	modifications = array(MultisigAccountModification, modifications_count)
good catch :+1:

2021-09-06 17:54 UTC, Jaguar0625 commented on nem/namespace/namespace_registration.cats
> +	parent_name = array(int8, parent_name_size) if 0xFFFFFFFF not equals parent_name_size
that was the best i could come up with :sob:

2021-09-06 17:55 UTC, Jaguar0625 commented on nem/mosaic/mosaic_supply_change.cats
> +	delta = Amount
both are nonnegative :D

2021-09-06 18:05 UTC, gimre-xymcity commented on nem/mosaic/mosaic_definition.cats
> +struct MosaicProperty
probably a comment, cause not quite sure how such restriction should look like.
enum of strings? probably makes no sense

2021-09-06 18:33 UTC, gimre-xymcity approved these changes

2021-09-06 18:34 UTC, Jaguar0625 commented on nem/account_key_link/account_key_link.cats
> +	remote_public_key = inline SizePrefixedPublicKey
we also have weird "data" property for buffers (e.g. Hash256) :sweat_smile:

2021-09-06 18:35 UTC, Jaguar0625 commented on nem/multisig/multisig.cats
> +	cosignatures = array(Cosignature, cosignatures_count)
per discussion `cosignatures_count` should always be present

2021-09-07 13:19 UTC, rg911 approved these changes

2021-09-07 14:22 UTC, merged